name: multi_store_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/men/
    - assets/images/inapp/
    - assets/images/women/
    - assets/images/shoes/
    - assets/images/electronics/
    - assets/images/beauty/
    - assets/images/kids/
    - assets/images/homegarden/
    - assets/images/accessories/
    - assets/images/bags/
    - assets/images/tabImages/
    - assets/images/supplierImages/
    - assets/images/welcome/


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 400
    - family: Kanun
      fonts:
        - asset: assets/fonts/Kanun_Bold.otf
          weight: 700
        - asset: assets/fonts/Kanun_Medium.otf
          weight: 500
        - asset: assets/fonts/Kanun_Regular.otf
          weight: 300

